version: 2

jobs:
  test:
    docker:
      - image: circleci/node:12.18.2
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ .Branch }}
      - run:
          name: "Install dependencies with npm"
          command: npm set cache .npm && npm ci
      - save_cache:
          key: npm-{{ .Branch }}
          paths:
            - ".npm"
      - run:
          name: "Run unit tests with jest and collect coverage"
          command: npm run test -- --ci --runInBand --coverage --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - run:
          name: "Send coverage report"
          command: ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
          environment:
            COVERALLS_FLAG_NAME: Unit
            COVERALLS_SERVICE_NAME: circleci
            COVERALLS_GIT_BRANCH: << pipeline.git.branch >>
            COVERALLS_SERVICE_JOB_NUMBER: << pipeline.number >>

workflows:
  version: 2
  test_only:
    jobs:
      - test
