version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.2
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test 