version: 2

jobs:
  test:
    docker:
      - image: circleci/node:12.18.2
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test

workflows:
  version: 2
  test_only:
    jobs:
      - test
